parameters:
    database_driver: pdo_mysql
    database_host: tunnel.pagodabox.com
    database_port: 3306
    database_name: mdesktop
    database_user: adella
    database_password: 4h5yTvmj
    
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null

    locale: pl
    
    secret: d3cd2a0d582b0ba0e7f8c421ba3fe494d6b40379
    
    database_path: null
