parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: devel_mdesktop
    database_user: root
    database_password: 5qrnaq3
    
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null

    locale: pl
    
    secret: d3cd2a0d582b0ba0e7f8c421ba3fe494d6b40379
    
    database_path: null
