parameters:
    database_driver: pdo_mysql
    database_host: %DATABASE_HOST%
    database_port: 3306
    database_name: %DATABASE_NAME%
    database_user: %DATABASE_USER%
    database_password: %DATABASE_PASSWORD%
    
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null

    locale: pl
    
    secret: d3cd2a0d582b0ba0e7f8c421ba3fe494d6b40379
    
    database_path: null
