root:
    pattern:  /
    defaults: { _controller: AcmeMainBundle:Track:index }
    
track:
    resource: "@AcmeMainBundle/Controller/TrackController.php"
    type:     annotation

content:
    resource: "@AcmeMainBundle/Controller/ContentController.php"
    type: annotation